using UnityEngine;

public class GunDamge : MonoBehaviour
{



    public int damage = 50;   // ğŸ”¥ ÙƒÙ„ Ø·Ù„Ù‚Ø© ØªØ³Ø¨Ø¨ 50 Ø¯Ø§Ù…Ø¬
    public float lifeTime = 3f;

    void Start()
    {
        Destroy(gameObject, lifeTime);  // Ø­Ø°Ù Ø§Ù„Ø±ØµØ§ØµØ© Ø¨Ø¹Ø¯ ÙˆÙ‚Øª
    }

    void OnCollisionEnter(Collision collision)
    {
        // Ù†Ø­Ø§ÙˆÙ„ Ù†Ø¬ÙŠØ¨ Ø³ÙƒØ±Ø¨Øª EnemyHealth Ù…Ù† Ø§Ù„Ø¬Ø³Ù… Ø§Ù„Ù…ØµØ·Ø¯Ù…
        EnemyHelth enemy = collision.gameObject.GetComponent<EnemyHelth>();
        if (enemy != null)
        {
            enemy.TakeDamage(damage);  // âš¡ Ø¶Ø±Ø± 50 Ù„ÙƒÙ„ Ø·Ù„Ù‚Ø©
        }

        Destroy(gameObject);  // Ø­Ø°Ù Ø§Ù„Ø±ØµØ§ØµØ© Ø¨Ø¹Ø¯ Ø§Ù„ØªØµØ§Ø¯Ù…
    }
}
